export const BROKER_TYPES = {
  immobilien: {
    label: 'Immobilien',
    defaultPage: '/pipeline',
    navOrder: ['dashboard', 'pipeline', 'markt', 'ai-agents', 'analytics', 'einstellungen'],
    accentColor: 'immobilien',
    pipelineStages: [
      { id: 'anfrage', label: 'Anfrage', order: 0 },
      { id: 'besichtigung', label: 'Besichtigung', order: 1 },
      { id: 'finanzierung', label: 'Finanzierung', order: 2 },
      { id: 'angebot', label: 'Angebot', order: 3 },
      { id: 'notartermin', label: 'Notartermin', order: 4 },
      { id: 'abgeschlossen', label: 'Abgeschlossen', order: 5 },
    ],
    leadFields: [
      { key: 'objectType', label: 'Objekttyp', type: 'select', options: ['Wohnung', 'Haus', 'Gewerbe', 'Grundstueck'] },
      { key: 'budget', label: 'Budget', type: 'currency', currency: 'EUR' },
      { key: 'location', label: 'Standort', type: 'text' },
      { key: 'sqm', label: 'Flaeche (m2)', type: 'number' },
      { key: 'timeline', label: 'Zeitrahmen', type: 'text' },
    ],
  },
  krypto: {
    label: 'Krypto',
    defaultPage: '/markt',
    navOrder: ['markt', 'dashboard', 'pipeline', 'ai-agents', 'analytics', 'einstellungen'],
    accentColor: 'krypto',
    pipelineStages: [
      { id: 'interesse', label: 'Interesse', order: 0 },
      { id: 'kyc', label: 'KYC-Pruefung', order: 1 },
      { id: 'portfolio', label: 'Portfolio-Planung', order: 2 },
      { id: 'investment', label: 'Investment', order: 3 },
      { id: 'monitoring', label: 'Monitoring', order: 4 },
      { id: 'abgeschlossen', label: 'Abgeschlossen', order: 5 },
    ],
    leadFields: [
      { key: 'asset', label: 'Asset', type: 'text' },
      { key: 'exchange', label: 'Boerse', type: 'select', options: ['Binance', 'Kraken', 'Coinbase', 'Bitpanda'] },
      { key: 'riskProfile', label: 'Risikoprofil', type: 'select', options: ['Konservativ', 'Moderat', 'Aggressiv'] },
      { key: 'investmentSize', label: 'Investitionsvolumen', type: 'currency', currency: 'EUR' },
    ],
  },
  finanz: {
    label: 'Finanz & Banking',
    defaultPage: '/dashboard',
    navOrder: ['dashboard', 'pipeline', 'markt', 'ai-agents', 'analytics', 'einstellungen'],
    accentColor: 'finanz',
    pipelineStages: [
      { id: 'kontakt', label: 'Erstkontakt', order: 0 },
      { id: 'beratung', label: 'Beratung', order: 1 },
      { id: 'analyse', label: 'Analyse', order: 2 },
      { id: 'angebot', label: 'Angebot', order: 3 },
      { id: 'abschluss', label: 'Abschluss', order: 4 },
      { id: 'abgeschlossen', label: 'Abgeschlossen', order: 5 },
    ],
    leadFields: [
      { key: 'produkttyp', label: 'Produkttyp', type: 'select', options: ['Kredit', 'Anlage', 'Vorsorge', 'Baufinanzierung'] },
      { key: 'anlagesumme', label: 'Anlagesumme', type: 'currency', currency: 'EUR' },
      { key: 'risikoklasse', label: 'Risikoklasse', type: 'select', options: ['Konservativ', 'Ausgewogen', 'Wachstum', 'Spekulativ'] },
      { key: 'laufzeit', label: 'Laufzeit', type: 'text' },
    ],
  },
  versicherung: {
    label: 'Versicherung',
    defaultPage: '/dashboard',
    navOrder: ['dashboard', 'pipeline', 'markt', 'ai-agents', 'analytics', 'einstellungen'],
    accentColor: 'versicherung',
    pipelineStages: [
      { id: 'kontakt', label: 'Erstkontakt', order: 0 },
      { id: 'bedarfsanalyse', label: 'Bedarfsanalyse', order: 1 },
      { id: 'angebot', label: 'Angebot', order: 2 },
      { id: 'antrag', label: 'Antrag', order: 3 },
      { id: 'police', label: 'Police', order: 4 },
      { id: 'abgeschlossen', label: 'Abgeschlossen', order: 5 },
    ],
    leadFields: [
      { key: 'versicherungsart', label: 'Versicherungsart', type: 'select', options: ['Leben', 'Sach', 'KFZ', 'Gesundheit', 'Haftpflicht'] },
      { key: 'laufzeit', label: 'Laufzeit', type: 'text' },
      { key: 'schadenhistorie', label: 'Schadenhistorie', type: 'text' },
      { key: 'praemie', label: 'Praemie', type: 'currency', currency: 'EUR' },
    ],
  },
  investment: {
    label: 'Investment-Banking',
    defaultPage: '/dashboard',
    navOrder: ['dashboard', 'pipeline', 'markt', 'ai-agents', 'analytics', 'einstellungen'],
    accentColor: 'investment',
    pipelineStages: [
      { id: 'akquise', label: 'Akquise', order: 0 },
      { id: 'duediligence', label: 'Due Diligence', order: 1 },
      { id: 'bewertung', label: 'Bewertung', order: 2 },
      { id: 'verhandlung', label: 'Verhandlung', order: 3 },
      { id: 'signing', label: 'Signing', order: 4 },
      { id: 'closing', label: 'Closing', order: 5 },
    ],
    leadFields: [
      { key: 'dealSize', label: 'Deal-Groesse', type: 'currency', currency: 'EUR' },
      { key: 'sector', label: 'Branche', type: 'text' },
      { key: 'transactionType', label: 'Transaktionstyp', type: 'select', options: ['M&A', 'IPO', 'Privatplatzierung', 'Venture'] },
      { key: 'timeline', label: 'Zeitrahmen', type: 'text' },
    ],
  },
};
